### ISSUE TITLE
耿坤 链表倒序 宿舍管理

### ISSUE THREAD

**Issue by KenMax233** [android-nuc/18-C-Train#17]
### 链表倒序_
#include<stdio.h>
#include<stdlib.h>
struct a 
{
   int b;
   struct a * next,* front;
};
struct a* p3;
struct a*creat()

{
       int n;
	   struct a * head;
	   struct a * p1, * p2;
	   n=0;
	   p1=p2=(struct a *)malloc(5);
	   printf("请输入数列(以00作为结束标志)：\n");
	   scanf("%d",&p1->b);
	   head=NULL;

	   while(p1->b!=00)
	   {
	     n=n+1;
		 if(n==1)head=p1;
		 else p2->next=p1;
		 p2=p1;
		 p1=(struct a *)malloc(5);
		 p1->front=p2;
		 scanf("%d",&p1->b);
	   }
	   p2->next=NULL;
	   p3=p1->front;
	   return head;

}
void print(struct a * head)
{
  struct a * p,* q;
  printf("now the list is:\n");
  p=head;
  head->front=NULL;
  if(head!=NULL)
  do
  {
	  printf("%d",p->b);
	  p=p->next;
  }while(p!=NULL);

 
  printf("now the reversed list is:\n");
  q=p3;
  do
  {
	  printf("%d",q->b);
	  q=q->front;
  }while(q!=NULL);

}

int main()
{
   struct a * head;
   head = creat();
   print(head);
}

## 宿舍管理

#include <stdio.h>
#include<malloc.h>
#include<stdlib.h>
#define LEN sizeof(struct Student)
struct Student
{
int num;
char name[20];
struct Student * next;
};
struct Student * creat()
{
int n;
struct Student * head;
struct Student * p1, * p2;
n=0;
p1=p2=(struct Student * )malloc(LEN);
printf("请依次输入学号、姓名、年龄、性别、宿舍号、床号等信息：\n（按学号从小到大顺序输入，且用逗号隔开，并以输入 0 结束）\n");
scanf("%d,%s",&p1->num,p1->name);
head=NULL;
while(p1->num!=0)
{
n=n+1;
if(n==1)head=p1;
else p2->next=p1;
p2=p1;
p1=(struct Student * )malloc(LEN);
scanf("%d,%s",&p1->num,p1->name);
   }
   p2->next=NULL;
   return head ;
}
void print (struct Student *head)
{
struct Student * p;
printf("\nThe information is:\n");
p=head;
if(head!=NULL)
{ printf("学号、姓名、年龄、性别、宿舍号、床号\n");
do
{
printf("%d,%s\n",p->num,p->name);
p=p->next;
   } while(p!=NULL);
}
else printf("fault!");
}
struct Student * insert(struct Student * head)
{
int num;
struct Student * p1, * p2, * p3;
printf("输入要插入的学号");
scanf("%d",&num);
p1=p2=head;
while(p1 != NULL)
{
	if(p1->num == num)
	{
		printf("已有相同编号！");
		return head;
	}
	else
	{
		p2=p1;
		p1=p1->next;
	}
}
		 printf("无重复学号，可插入.\n");
		 p3=(struct Student * )malloc(LEN);
		 p3->next = NULL;
		 printf("请输所要插入的信息（格式同上）：\n用逗号隔开）\n");
		 scanf("%d,%s",&p3->num,p3->name);
		 p2->next = p3;
		 return head;
}
struct Student * del(struct Student * head)
{
int flag=1;
int num;
struct Student * p, * q;
printf("输入要删除的学号：");
scanf("%d",&num);
p=q=head;
while(p!=NULL && flag)
{
if(p->num == num)
{
if(p = head)
{head=p->next;free(p);}
else{q->next = p->next;free(p);}
flag=0;
}
else
{
q=p;
p=p->next;
}
}
if(flag)
printf("没找到可删除的数据！");
else
printf("删除成功！");
return head;
}
void chaxun(struct Student *head)
{
int flag = 1;
int num;
struct Student * p;
printf("输入要查询的学号：");
scanf("%d",&num);
p=head;
while((p != NULL) && flag)
{
	if(p->num == num)
	{
		printf("%d,%s\n",p->num,p->name);
		flag = 0;
	}
	else
		p=p->next;
}
		if(flag = 1) printf("未查询到！");

}
int save (struct Student * head)
{
struct Student * p;
FILE * fp;
p = head;
if ((fp = fopen("a.txt", "ab+")) == NULL)
{
printf("无法打开");
exit (0);
}
while (p != NULL)
{
fwrite(p, sizeof(struct Student), 1, fp);
p = p->next;
}
printf("保存成功！");
fclose(fp);
return 1;
}
int main()
{
int u;
struct Student * head;
  head=creat(); 
	do
  {
  printf("\n请输入对应代号执行相关操作：\n");
  printf("输入数字1-----输出\n");
  printf("输入数字2-----删除\n");
  printf("输入数字3-----插入\n");
  printf("输入数字4-----查询\n");
  printf("输入数字5-----保存\n");
  printf("输入数字6-----退出\n");
  scanf("%d",&u);
switch(u)
{
   case 1:{print(head);break;}
   case 2:{head = del(head); break; }
   case 3:{head = insert(head);break;}
   case 4:{chaxun(head);}
   case 5:{save(head);}
   case 6:{break;}
   default:printf("无效操作");break;
	 }
   }while(u!=6);
	return(0);
}

**Comment by wanghao15536870732** [comment]
+ 编译不通过，请修改完善

**Comment by wmpscc** [comment]
- 链表倒序不符合要求（为对原链表实际进行操作）
- 缺少矩阵乘法代码
